/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Connection.Koneksi;
import Dao.CostDriverDao;
import Dao.HppDao;
import Dao.ReportDao;
import Dao.TableDao;
import Dao.TarifDao;
import Model.tbKlasifikasi;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ariramadhan
 */
public class FormPerhitungan extends javax.swing.JFrame {

    CostDriverDao cd = new CostDriverDao();
    TarifDao td = new TarifDao();
    Koneksi con;
    ResultSet res;
    Statement st;

    TableDao tbd = new TableDao();
    private String rsCD[][];
    private String rsHasil[][];
    String[] namaKolomCD = {"Id", "Jenis", "Total Unit", "Total KWH", "Total Inspeksi", "Luas Area"};
    int jmlKolomCD = namaKolomCD.length;
    int[] lebarCD = {100, 250, 150, 150, 200, 200};

    String[] namaKolom = {"Id", "Jenis", "Total HPP", "HPP Per Unit"};
    int jmlKolom = namaKolom.length;
    int[] lebar = {100, 150, 150, 150};

    public FormPerhitungan() {
        initComponents();
        setLocationRelativeTo(this);
        addJenis();

    }

    private void RefreshCD() {
        cbJenis.setSelectedIndex(0);
        txtJumlahKwh.setText("");
        txtJmlhUnit.setText("");
        txtTotalKwh.setText("");
        txtJumlahKwh.setText("");
        txtTotalKwh.setText("");
        txtTotalInspeksi.setText("");
        txtJumlahInspeksi.setText("");
        txtLuasArea.setText("");
    }

    private void addJenis() {
        ArrayList<String> dataJenis = new ArrayList<>();

        dataJenis = td.ListJenis();

        for (int a = 0; a < dataJenis.size(); a++) {
            cbJenisLemari.addItem(dataJenis.get(a).toString());
        }
    }

    private void GetHppAwal(String lemari) {
        con = new Koneksi();
        try {
            st = con.connect().createStatement();
            res = st.executeQuery("SELECT *FROM tb_hpp WHERE jenis='" + lemari + "'");
            while (res.next()) {
                int bahanBaku = (Integer.parseInt(res.getString("bahan_baku")));
                int tkl = (Integer.parseInt(res.getString("tkl")));

                int unit = Integer.parseInt(txtUnitProduk2.getText());

                txtTKL2.setText(String.valueOf(unit * tkl));
                txtBahanBaku2.setText(String.valueOf(unit * bahanBaku));

            }
        } catch (Exception e) {

        }
    }

    private void RefreshHasil() {
        cbJenisLemari.setSelectedIndex(0);
        txtUnitProduk2.setText("");
        txtBebanUnitProduk2.setText("");
        txtKwh2.setText("");
        txtInspeksi2.setText("");
        txtProduk2.setText("");
        txtLuasArea2.setText("");
        txtBahanBaku2.setText("");
        txtTKL2.setText("");
        txtOverhead2.setText("");
        txtHppPerUnit2.setText("");
        txtTotalHpp2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtJmlhUnit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtJumlahKwh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtJumlahInspeksi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLuasArea = new javax.swing.JTextField();
        btnSaveCostDriver = new javax.swing.JButton();
        btnDeleteCostDriver = new javax.swing.JButton();
        btnRefreshCostDriver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCD = new javax.swing.JTable();
        txtTotalKwh = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtTotalInspeksi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBiayaPenolong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBiayaDepresiasiMesin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPool1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTotalUnitProduksi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPoolRate1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBiayaListrik = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPoolRate2 = new javax.swing.JTextField();
        txtTotalPool2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBiayaPemeliharaanMesin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPoolRate3 = new javax.swing.JTextField();
        txtTotalPool3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtBiayaPemasaran = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTotalPool4 = new javax.swing.JTextField();
        txtPoolRate4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTotalPool5 = new javax.swing.JTextField();
        txtBiayaPemeliharaanBangunan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtPoolRate5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtBiayaDepresiasiBangunan = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtLuasAreaTotal = new javax.swing.JTextField();
        btnTampilHasilTarif = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        txtTotalKWH = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        totalInspeksi1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtUnitProduk2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cbJenisLemari = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtInspeksi2 = new javax.swing.JTextField();
        txtProduk2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtKwh2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtLuasArea2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtBahanBaku2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtTKL2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtOverhead2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtTotalHpp2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtBebanUnitProduk2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtHppPerUnit2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnSave2 = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("JUMLAH UNIT");

        txtJmlhUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJmlhUnitKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("JENIS LEMARI");

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "LEMARI MINIMALIS", "LEMARI KACA" }));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("KWH/ UNIT");

        txtJumlahKwh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKwhKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKwhKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("INSPEKSI/ JAM");

        txtJumlahInspeksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahInspeksiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahInspeksiKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("LUAS AREA (m2)");

        txtLuasArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLuasAreaKeyTyped(evt);
            }
        });

        btnSaveCostDriver.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnSaveCostDriver.setText("SAVE");
        btnSaveCostDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCostDriverActionPerformed(evt);
            }
        });

        btnDeleteCostDriver.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnDeleteCostDriver.setText("DELETE");
        btnDeleteCostDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCostDriverActionPerformed(evt);
            }
        });

        btnRefreshCostDriver.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnRefreshCostDriver.setText("REFRESH");
        btnRefreshCostDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCostDriverActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCD);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTotalKwh.setEditable(false);
        txtTotalKwh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKwhKeyTyped(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel37.setText("TOTAL KWH");

        jLabel38.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel38.setText("TOTAL INSPEKSI");

        txtTotalInspeksi.setEditable(false);
        txtTotalInspeksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalInspeksiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtJmlhUnit, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtJumlahKwh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel2))
                                                .addGap(50, 50, 50)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel37)
                                                .addGap(64, 64, 64))
                                            .addComponent(txtTotalKwh))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSaveCostDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteCostDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(txtLuasArea)
                            .addComponent(btnRefreshCostDriver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJumlahInspeksi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalInspeksi)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 28, Short.MAX_VALUE)))))
                        .addGap(333, 333, 333))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlahInspeksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalInspeksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLuasArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJmlhUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnSaveCostDriver)
                    .addComponent(btnDeleteCostDriver)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahKwh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshCostDriver)
                    .addComponent(txtTotalKwh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("COST DRIVER", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("BIAYA BAHAN PENOLONG");

        txtBiayaPenolong.setEditable(false);
        txtBiayaPenolong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBiayaPenolongKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("BIAYA DEPRESIASI MESIN");

        txtBiayaDepresiasiMesin.setEditable(false);
        txtBiayaDepresiasiMesin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBiayaDepresiasiMesinKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("TOTAL POOL 1");

        txtTotalPool1.setEditable(false);
        txtTotalPool1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalPool1KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("JUMLAH UNIT PRODUKSI");

        txtTotalUnitProduksi.setEditable(false);
        txtTotalUnitProduksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalUnitProduksiKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("POOL RATE 1");

        txtPoolRate1.setEditable(false);
        txtPoolRate1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPoolRate1KeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("BIAYA LISTRIK");

        txtBiayaListrik.setEditable(false);
        txtBiayaListrik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBiayaListrikKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("TOTAL POOL 2");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("POOL RATE 2");

        txtPoolRate2.setEditable(false);
        txtPoolRate2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPoolRate2KeyTyped(evt);
            }
        });

        txtTotalPool2.setEditable(false);
        txtTotalPool2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalPool2KeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("BIAYA PEMELIHARAAN MESIN");

        txtBiayaPemeliharaanMesin.setEditable(false);
        txtBiayaPemeliharaanMesin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBiayaPemeliharaanMesinKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("TOTAL POOL 3");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("POOL RATE 3");

        txtPoolRate3.setEditable(false);
        txtPoolRate3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPoolRate3KeyTyped(evt);
            }
        });

        txtTotalPool3.setEditable(false);
        txtTotalPool3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalPool3KeyTyped(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txtBiayaPemasaran.setEditable(false);
        txtBiayaPemasaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBiayaPemasaranKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel18.setText("TOTAL POOL 4");

        txtTotalPool4.setEditable(false);
        txtTotalPool4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalPool4KeyTyped(evt);
            }
        });

        txtPoolRate4.setEditable(false);
        txtPoolRate4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPoolRate4KeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel19.setText("POOL RATE 4");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel17.setText("BIAYA PEMASARAN");

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel21.setText("TOTAL POOL 5");

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel20.setText("BIAYA PEMELIHARAAN BANGUNAN");

        txtTotalPool5.setEditable(false);
        txtTotalPool5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalPool5KeyTyped(evt);
            }
        });

        txtBiayaPemeliharaanBangunan.setEditable(false);
        txtBiayaPemeliharaanBangunan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBiayaPemeliharaanBangunanKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel22.setText("POOL RATE 5");

        txtPoolRate5.setEditable(false);
        txtPoolRate5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPoolRate5KeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel23.setText("BIAYA DEPRESIASI BANGUNAN");

        txtBiayaDepresiasiBangunan.setEditable(false);
        txtBiayaDepresiasiBangunan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBiayaDepresiasiBangunanKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel24.setText("JUMLAH PEMAKAIAN LUAS AREA (m2)");

        txtLuasAreaTotal.setEditable(false);
        txtLuasAreaTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLuasAreaTotalKeyTyped(evt);
            }
        });

        btnTampilHasilTarif.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnTampilHasilTarif.setText("TAMPILKAN HASIL PENENTUAN TARIF");
        btnTampilHasilTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilHasilTarifActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel39.setText("TOTAL KWH");

        txtTotalKWH.setEditable(false);
        txtTotalKWH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKWHKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(208, 208, 208))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(btnTampilHasilTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTotalKWH, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLuasAreaTotal)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(txtTotalPool4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txtPoolRate4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtBiayaPemasaran, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBiayaPemeliharaanBangunan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBiayaDepresiasiBangunan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalPool5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22)
                                    .addComponent(txtPoolRate5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalKWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBiayaPemasaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPool4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPoolRate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBiayaPemeliharaanBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBiayaDepresiasiBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLuasAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPoolRate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPool5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTampilHasilTarif)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel40.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel40.setText("TOTAL INSPEKSI");

        totalInspeksi1.setEditable(false);
        totalInspeksi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalInspeksi1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(txtTotalPool1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(txtPoolRate1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtBiayaDepresiasiMesin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBiayaPenolong, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTotalUnitProduksi, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel11)
                    .addComponent(txtBiayaListrik, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtTotalPool3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txtPoolRate3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBiayaPemeliharaanMesin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalPool2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(txtPoolRate2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(totalInspeksi1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalUnitProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBiayaPenolong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBiayaDepresiasiMesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPool1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPoolRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtBiayaListrik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalPool2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPoolRate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBiayaPemeliharaanMesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalInspeksi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPool3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPoolRate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PENENTUAN TARIF KELOMPOK", jPanel4);

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel25.setText("UNIT PRODUK");

        txtUnitProduk2.setEditable(false);
        txtUnitProduk2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnitProduk2KeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel26.setText("JENIS LEMARI (DATA DARI COST DRIVER)");

        cbJenisLemari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cbJenisLemari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJenisLemariItemStateChanged(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel27.setText("JAM INSPEKSI");

        txtInspeksi2.setEditable(false);
        txtInspeksi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInspeksi2KeyTyped(evt);
            }
        });

        txtProduk2.setEditable(false);
        txtProduk2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProduk2KeyTyped(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel28.setText("PRODUK");

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel29.setText("KWH");

        txtKwh2.setEditable(false);
        txtKwh2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKwh2KeyTyped(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel30.setText("LUAS AREA");

        txtLuasArea2.setEditable(false);
        txtLuasArea2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLuasArea2KeyTyped(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel31.setText("BIAYA BAHAN BAKU");

        txtBahanBaku2.setEditable(false);
        txtBahanBaku2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBahanBaku2KeyTyped(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel32.setText("BIAYA TENAGA KERJA LANGSUNG");

        txtTKL2.setEditable(false);
        txtTKL2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTKL2KeyTyped(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel33.setText("BIAYA OVERHEAD PABRIK");

        txtOverhead2.setEditable(false);
        txtOverhead2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOverhead2KeyTyped(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel34.setText("TOTAL HPP");

        txtTotalHpp2.setEditable(false);
        txtTotalHpp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalHpp2KeyTyped(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel35.setText("BEBAN UNIT PRODUK");

        txtBebanUnitProduk2.setEditable(false);
        txtBebanUnitProduk2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBebanUnitProduk2KeyTyped(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel36.setText("TOTAL HPP PER UNIT");

        txtHppPerUnit2.setEditable(false);
        txtHppPerUnit2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHppPerUnit2KeyTyped(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnSave2.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnSave2.setText("CETAK");
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(btnSave2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave2)
                .addContainerGap())
        );

        btnSave1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnSave1.setText("SAVE");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        btnDelete1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnDelete1.setText("DELETE");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnCancel1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnCancel1.setText("REFRESH");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbJenisLemari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(txtUnitProduk2)
                    .addComponent(jLabel29)
                    .addComponent(txtKwh2)
                    .addComponent(jLabel27)
                    .addComponent(txtInspeksi2)
                    .addComponent(jLabel28)
                    .addComponent(txtProduk2)
                    .addComponent(txtLuasArea2)
                    .addComponent(jLabel30)
                    .addComponent(txtBahanBaku2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel35)
                    .addComponent(txtBebanUnitProduk2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                .addComponent(txtOverhead2)
                                .addComponent(txtTKL2)
                                .addComponent(txtTotalHpp2))
                            .addComponent(txtHppPerUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(jLabel32)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtTKL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbJenisLemari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(64, 64, 64))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel33)
                                                .addComponent(jLabel25))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtOverhead2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtUnitProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(64, 64, 64))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel34)
                                        .addComponent(jLabel35))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTotalHpp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBebanUnitProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKwh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHppPerUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(btnSave1)
                    .addComponent(btnDelete1)
                    .addComponent(btnCancel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtInspeksi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLuasArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBahanBaku2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PROSEDUR TAHAP 2", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJmlhUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlhUnitKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) || (karakter == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            evt.consume();
        }

        if (karakter == KeyEvent.VK_SPACE) {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtJmlhUnitKeyTyped

    private void txtJumlahKwhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKwhKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKwhKeyTyped

    private void txtJumlahInspeksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahInspeksiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahInspeksiKeyTyped

    private void txtLuasAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuasAreaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuasAreaKeyTyped

    private void btnSaveCostDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCostDriverActionPerformed
        // TODO add your handling code here:
        cd.Save(cbJenis.getSelectedItem().toString(), Integer.parseInt(txtJmlhUnit.getText()), txtTotalKwh.getText(), txtTotalInspeksi.getText(), txtLuasArea.getText());
        RefreshCD();
    }//GEN-LAST:event_btnSaveCostDriverActionPerformed

    private void btnDeleteCostDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCostDriverActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah akan di hapus data ini ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            cd.Delete(cd.getId());
        }
        RefreshCD();
    }//GEN-LAST:event_btnDeleteCostDriverActionPerformed

    private void txtBiayaPenolongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiayaPenolongKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiayaPenolongKeyTyped

    private void txtBiayaDepresiasiMesinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiayaDepresiasiMesinKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiayaDepresiasiMesinKeyTyped

    private void txtTotalPool1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPool1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPool1KeyTyped

    private void txtTotalUnitProduksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalUnitProduksiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalUnitProduksiKeyTyped

    private void txtPoolRate1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoolRate1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoolRate1KeyTyped

    private void txtBiayaListrikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiayaListrikKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiayaListrikKeyTyped

    private void txtPoolRate2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoolRate2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoolRate2KeyTyped

    private void txtTotalPool2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPool2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPool2KeyTyped

    private void txtBiayaPemeliharaanMesinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiayaPemeliharaanMesinKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiayaPemeliharaanMesinKeyTyped

    private void txtPoolRate3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoolRate3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoolRate3KeyTyped

    private void txtTotalPool3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPool3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPool3KeyTyped

    private void txtBiayaPemasaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiayaPemasaranKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiayaPemasaranKeyTyped

    private void txtTotalPool4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPool4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPool4KeyTyped

    private void txtPoolRate4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoolRate4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoolRate4KeyTyped

    private void txtBiayaPemeliharaanBangunanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiayaPemeliharaanBangunanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiayaPemeliharaanBangunanKeyTyped

    private void txtPoolRate5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoolRate5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoolRate5KeyTyped

    private void txtTotalPool5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPool5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPool5KeyTyped

    private void txtBiayaDepresiasiBangunanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiayaDepresiasiBangunanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiayaDepresiasiBangunanKeyTyped

    private void txtLuasAreaTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuasAreaTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuasAreaTotalKeyTyped

    private void txtLuasArea2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuasArea2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuasArea2KeyTyped

    private void txtKwh2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKwh2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKwh2KeyTyped

    private void txtProduk2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProduk2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduk2KeyTyped

    private void txtInspeksi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInspeksi2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInspeksi2KeyTyped

    private void txtUnitProduk2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnitProduk2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitProduk2KeyTyped

    private void txtBahanBaku2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBahanBaku2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBahanBaku2KeyTyped

    private void txtTKL2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKL2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKL2KeyTyped

    private void txtOverhead2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOverhead2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOverhead2KeyTyped

    private void txtTotalHpp2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalHpp2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHpp2KeyTyped

    private void txtBebanUnitProduk2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBebanUnitProduk2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBebanUnitProduk2KeyTyped

    private void txtHppPerUnit2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHppPerUnit2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHppPerUnit2KeyTyped

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        if (cbJenisLemari.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Jenis Lemari !");
        } else if (txtPoolRate5.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan Hitung Tarif Terlebih Dahulu !");
        } else {
            td.Save(cbJenisLemari.getSelectedItem().toString(), txtUnitProduk2.getText(), txtBebanUnitProduk2.getText(),
                    txtKwh2.getText(), txtInspeksi2.getText(), txtProduk2.getText(),
                    txtLuasArea2.getText(), txtBahanBaku2.getText(), txtTKL2.getText(),
                    txtOverhead2.getText(), txtTotalHpp2.getText(), txtHppPerUnit2.getText());
            RefreshHasil();
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah akan di hapus data ini ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            td.Delete(td.getIdHasil());
        }
        RefreshHasil();
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
        // TODO add your handling code here:
        ReportDao rd = new ReportDao();
        
        if(jTable2.getRowCount()==0){
            JOptionPane.showConfirmDialog(null, "Data Hpp Belum Tersedia, Data Gagal di Cetak !");
        }else{
             rd.CetakLaporanHistori();
        }
         
    }//GEN-LAST:event_btnSave2ActionPerformed

    private void txtTotalKwhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKwhKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKwhKeyTyped

    private void txtTotalInspeksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalInspeksiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalInspeksiKeyTyped

    private void txtJumlahKwhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKwhKeyReleased
        // TODO add your handling code here:
        double kwh = Double.parseDouble(txtJumlahKwh.getText());
        double unit = Double.parseDouble(txtJmlhUnit.getText());
        txtTotalKwh.setText(String.valueOf(kwh * unit));

    }//GEN-LAST:event_txtJumlahKwhKeyReleased

    private void txtJumlahInspeksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahInspeksiKeyReleased
        // TODO add your handling code here:
        double inspeksi = Double.parseDouble(txtJumlahInspeksi.getText());
        double unit = Double.parseDouble(txtJmlhUnit.getText());
        txtTotalInspeksi.setText(String.valueOf(inspeksi * unit));
    }//GEN-LAST:event_txtJumlahInspeksiKeyReleased

    private void tblCDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCDMouseClicked
        // TODO add your handling code here:
        int click = tblCD.getSelectedRow();
        cd.setId(Integer.parseInt(tblCD.getValueAt(click, 0).toString()));
    }//GEN-LAST:event_tblCDMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        rsCD = cd.ShowData();
        tbd.SetTabel(tblCD, rsCD, namaKolomCD, jmlKolomCD, lebarCD);

        rsHasil = td.ShowData();
        tbd.SetTabel(jTable2, rsHasil, namaKolom, jmlKolom, lebar);

        int totalData = tblCD.getRowCount();
        int jumlahUnit = 0;
        int totalArea = 0;
        double jumlahKWH = 0.0;
        double totalInspeksi = 0.0;

        for (int a = 0; a < totalData; a++) {

            jumlahUnit += Integer.parseInt(tblCD.getValueAt(a, 2).toString());
            jumlahKWH += Double.parseDouble(tblCD.getValueAt(a, 3).toString());
            totalArea += Integer.parseInt(tblCD.getValueAt(a, 5).toString());
            totalInspeksi += Double.parseDouble(tblCD.getValueAt(a, 4).toString());
        }

        txtTotalUnitProduksi.setText(String.valueOf(jumlahUnit));
        txtLuasAreaTotal.setText(String.valueOf(totalArea));
        txtTotalKWH.setText(String.valueOf(jumlahKWH));
        totalInspeksi1.setText(String.valueOf(totalInspeksi));

    }//GEN-LAST:event_formWindowActivated

    private void btnRefreshCostDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCostDriverActionPerformed
        // TODO add your handling code here:
        RefreshCD();
    }//GEN-LAST:event_btnRefreshCostDriverActionPerformed

    private void btnTampilHasilTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilHasilTarifActionPerformed
        // TODO add your handling code here:
        int rowTable = tblCD.getRowCount();
        int rowJenis = cbJenis.getItemCount();

        if (rowTable != rowJenis) {
            JOptionPane.showMessageDialog(null, "Data barang belum ditambahkan seluruhnya, Silahkan di Inpur Terlebih Dahulu!!");
        
        } else {

            ArrayList<tbKlasifikasi> list = new ArrayList<>();
            list = td.ListTarif();
            txtBiayaPenolong.setText(list.get(0).getBiayaPenolong());
            txtBiayaDepresiasiMesin.setText(list.get(0).getBiayaMesin());
            txtBiayaListrik.setText(list.get(0).getBiayaListrik());
            txtBiayaPemeliharaanMesin.setText(list.get(0).getBiayaMtnMesin());
            txtBiayaPemasaran.setText(list.get(0).getBiayaPemasaran());
            txtBiayaPemeliharaanBangunan.setText(list.get(0).getBiayaMtnBangunan());
            txtBiayaDepresiasiBangunan.setText(list.get(0).getBiayaBangunan());

            double totalPool1 = 0.0;
            double totalPool2 = 0.0;
            double totalPool3 = 0.0;
            double totalPool4 = 0.0;
            double totalPool5 = 0.0;

            double unit = Double.parseDouble(txtTotalUnitProduksi.getText());
            double penolong = Double.parseDouble(txtBiayaPenolong.getText());
            double depMesin = Double.parseDouble(txtBiayaDepresiasiMesin.getText());
            totalPool1 = penolong + depMesin;
            txtTotalPool1.setText(String.valueOf(totalPool1));
            txtPoolRate1.setText(String.valueOf(String.format("%.2f", totalPool1 / unit)));

            double listrik = Double.parseDouble(txtBiayaListrik.getText());

            totalPool2 = listrik;
            txtTotalPool2.setText(String.valueOf(totalPool2));
            txtPoolRate2.setText(String.valueOf(String.format("%.2f", listrik / Double.parseDouble(txtTotalKWH.getText()))));

            double mtnMesin = Double.parseDouble(txtBiayaPemeliharaanMesin.getText());
            totalPool3 = mtnMesin;
            txtTotalPool3.setText(String.valueOf(totalPool3));
            txtPoolRate3.setText(String.valueOf(String.format("%.2f", mtnMesin / Double.parseDouble(totalInspeksi1.getText()))));

            double pemasaran = Double.parseDouble(txtBiayaPemasaran.getText());

            totalPool4 = pemasaran;
            txtTotalPool4.setText(String.valueOf(totalPool4));
            txtPoolRate4.setText(String.valueOf(String.format("%.2f", pemasaran / unit)));

            double mtnBangunan = Double.parseDouble(txtBiayaPemeliharaanBangunan.getText());
            double depBangunan = Double.parseDouble(txtBiayaDepresiasiBangunan.getText());
            double luasArea = Double.parseDouble(txtLuasAreaTotal.getText());
            totalPool5 = mtnBangunan + depBangunan;
            txtTotalPool5.setText(String.valueOf(totalPool5));
            txtPoolRate5.setText(String.valueOf(String.format("%.2f", totalPool5 / luasArea)));

            btnTampilHasilTarif.setEnabled(false);
        }

    }//GEN-LAST:event_btnTampilHasilTarifActionPerformed

    private void cbJenisLemariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJenisLemariItemStateChanged
        // TODO add your handling code here:
        con = new Koneksi();
        try {
            st = con.connect().createStatement();
            res = st.executeQuery("SELECT *FROM tb_costdriver WHERE jenis_lemari='" + cbJenisLemari.getSelectedItem().toString() + "'");
            while (res.next()) {
                txtUnitProduk2.setText(res.getString("jumlah_unit"));
                //hitung
                double unit = Double.parseDouble(txtUnitProduk2.getText());
                txtBebanUnitProduk2.setText(String.valueOf(Double.parseDouble(txtPoolRate1.getText()) * unit));
                txtKwh2.setText(String.valueOf((Double.parseDouble(res.getString("total_kwh"))) * (Double.parseDouble(txtPoolRate2.getText()))));
                txtInspeksi2.setText(String.valueOf(Double.parseDouble(res.getString("total_inspeksi")) * Double.parseDouble(txtPoolRate3.getText())));
                txtProduk2.setText(String.valueOf(unit * Double.parseDouble(txtPoolRate4.getText())));
                txtLuasArea2.setText(String.valueOf(Double.parseDouble(res.getString("luas_area")) * Double.parseDouble(txtPoolRate5.getText())));

                GetHppAwal(cbJenisLemari.getSelectedItem().toString());

                double pool1 = Double.parseDouble(txtBebanUnitProduk2.getText());
                double pool2 = Double.parseDouble(txtKwh2.getText());
                double pool3 = Double.parseDouble(txtInspeksi2.getText());
                double pool4 = Double.parseDouble(txtProduk2.getText());
                double pool5 = Double.parseDouble(txtLuasArea2.getText());

                txtOverhead2.setText(String.valueOf(Math.round(pool1 + pool2 + pool3 + pool4 + pool5)));

                double tkl = Double.parseDouble(txtTKL2.getText());
                double bahanBaku = Double.parseDouble(txtBahanBaku2.getText());
                double overhead = Double.parseDouble(txtOverhead2.getText());
                txtTotalHpp2.setText(String.valueOf(Math.round(tkl + bahanBaku + overhead)));

                txtHppPerUnit2.setText(String.valueOf(Math.round(Double.parseDouble(txtTotalHpp2.getText()) / unit)));

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbJenisLemariItemStateChanged

    private void txtTotalKWHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKWHKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKWHKeyTyped

    private void totalInspeksi1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalInspeksi1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_totalInspeksi1KeyTyped

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:
        RefreshHasil();
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int click = jTable2.getSelectedRow();
        td.setIdHasil(Integer.parseInt(jTable2.getValueAt(click, 0).toString()));
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPerhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPerhitungan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDeleteCostDriver;
    private javax.swing.JButton btnRefreshCostDriver;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton btnSaveCostDriver;
    private javax.swing.JButton btnTampilHasilTarif;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbJenisLemari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblCD;
    private javax.swing.JTextField totalInspeksi1;
    private javax.swing.JTextField txtBahanBaku2;
    private javax.swing.JTextField txtBebanUnitProduk2;
    private javax.swing.JTextField txtBiayaDepresiasiBangunan;
    private javax.swing.JTextField txtBiayaDepresiasiMesin;
    private javax.swing.JTextField txtBiayaListrik;
    private javax.swing.JTextField txtBiayaPemasaran;
    private javax.swing.JTextField txtBiayaPemeliharaanBangunan;
    private javax.swing.JTextField txtBiayaPemeliharaanMesin;
    private javax.swing.JTextField txtBiayaPenolong;
    private javax.swing.JTextField txtHppPerUnit2;
    private javax.swing.JTextField txtInspeksi2;
    private javax.swing.JTextField txtJmlhUnit;
    private javax.swing.JTextField txtJumlahInspeksi;
    private javax.swing.JTextField txtJumlahKwh;
    private javax.swing.JTextField txtKwh2;
    private javax.swing.JTextField txtLuasArea;
    private javax.swing.JTextField txtLuasArea2;
    private javax.swing.JTextField txtLuasAreaTotal;
    private javax.swing.JTextField txtOverhead2;
    private javax.swing.JTextField txtPoolRate1;
    private javax.swing.JTextField txtPoolRate2;
    private javax.swing.JTextField txtPoolRate3;
    private javax.swing.JTextField txtPoolRate4;
    private javax.swing.JTextField txtPoolRate5;
    private javax.swing.JTextField txtProduk2;
    private javax.swing.JTextField txtTKL2;
    private javax.swing.JTextField txtTotalHpp2;
    private javax.swing.JTextField txtTotalInspeksi;
    private javax.swing.JTextField txtTotalKWH;
    private javax.swing.JTextField txtTotalKwh;
    private javax.swing.JTextField txtTotalPool1;
    private javax.swing.JTextField txtTotalPool2;
    private javax.swing.JTextField txtTotalPool3;
    private javax.swing.JTextField txtTotalPool4;
    private javax.swing.JTextField txtTotalPool5;
    private javax.swing.JTextField txtTotalUnitProduksi;
    private javax.swing.JTextField txtUnitProduk2;
    // End of variables declaration//GEN-END:variables
}
